name: Database Migration
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x  # Replace '6.0.x' with the specific .NET 6 version you need
          
      - name: Restore dependencies
        working-directory: ./DataBaseMigration/DataBaseMigration  # Adjust as needed
        run: dotnet restore

      - name: Build Database Migration
        working-directory: ./DataBaseMigration/DataBaseMigration  # Adjust as needed
        run: dotnet build

      - name: Run Database Migration
        shell: pwsh
        run: |
           $output = dotnet run --project ./DataBaseMigration/DataBaseMigration.csproj
           if ($output -like "*Database migration successful!*") {
           Write-Host "Database migration was successful!"
           }
           else {
           Write-Host "Database migration failed!"
           Write-Host "Cancelling the workflow..."
      
              $apiUrl = "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/cancel"
              $headers = @{
              Authorization = "token $env:GITHUB_TOKEN"
              Accept = "application/vnd.github.v3+json"
           }
            Invoke-RestMethod -Uri $apiUrl -Headers $headers -Method Post
           }
