name: Database Migration

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger on

jobs:
  db-up-migration:
    runs-on: windows-latest  # Use the Windows runner if you're on Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1  # or the version you need



      - name: Execute DbUp Migrations
        run: |
         dotnet build "DataBaseMigration/DataBaseMigration.csproj"
         dotnet run --project "DataBaseMigration/DataBaseMigration.csproj"
