name: Database Migration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1

      - name: Restore dependencies
        run: dotnet restore

      - name: List Repository Contents
        run: |
          ls -R
          
      - name: Build and Run Database Migration
        working-directory: ./DataBaseMigration/DataBaseMigration  # Adjust as needed
        run: |
          dotnet build ./DataBaseMigration/DataBaseMigration/DataBaseMigration.csproj
          dotnet run --project ./DataBaseMigration/DataBaseMigration/DataBaseMigration.csproj
