name: Database Migration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps :
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x  # Replace '6.0.x' with the specific .NET 6 version you need

      - name: Restore dependencies
        working-directory: ./DataBaseMigration  # Adjust as needed
        run: dotnet restore

      - name: Build Database Migration
        working-directory: ./DataBaseMigration  # Adjust as needed
        run: dotnet build

      - name: Run Database Migration
        id: run-migration
        working-directory: ./DataBaseMigration  # Adjust as needed
        run: |
           dotnet run --project ./DataBaseMigration.csproj -- -c DatabaseMigrationConfiguration --migrate

      - name: Migration Succeeded
        if: steps.start-migration.outputs.result == 'success'
        run: |
          echo "The migration succeeded. You can add additional steps or notifications here."
