name: Database Migration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1

      - name: List Files
        run: ls -R 

      - name: Build and Run Database Migration
        run: |
              dotnet build "https://github.com/siddhi17-create/main/raw/main/DataBaseMigration/DataBaseMigration/DataBaseMigration/DataBaseMigration.csproj"
              dotnet run "https://github.com/siddhi17-create/main/raw/main/DataBaseMigration/DataBaseMigration/DataBaseMigration/DataBaseMigration.csproj"
