name: Database Migration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        working-directory:  ./DataBaseMigration/DataBaseMigration
        run: dotnet restore


      - name: List Repository Contents
        run: |
          ls -R
          
      - name: Build and Run Database Migration
        working-directory: ./DataBaseMigration/DataBaseMigration  # Adjust as needed
        run: |
          dotnet build 
          dotnet run --project ./DataBaseMigration/DataBaseMigration/DataBaseMigration.csproj
