name: Database Migration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x  # Replace '6.0.x' with the specific .NET 6 version you need

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Database Migration
        run: dotnet build
        working-directory: ./DataBaseMigration/DataBaseMigration/DataBaseMigration  # Adjust as needed

      - name: Run Database Migration
        run: dotnet run --project ./DataBaseMigration/DataBaseMigration/DataBaseMigration.csproj
        working-directory: ./DataBaseMigration/DataBaseMigration/DataBaseMigration  # Adjust as needed
