name: Database Migration

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger on

jobs:
  db-up-migration:
    runs-on: windows-latest  # Use the Windows runner if you're on Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1  # or the version you need

      - name: Restore dependencies
        run: |
          dotnet restore
          dotnet tool restore  # Restore tools like DbUp if needed

      - name: Execute DbUp Migrations
        run: |
          dotnet "D:\GitTest\DataBaseMigration\DataBaseMigration\DataBaseMigration\dbup-cli.dll" upgrade -c "Server=localhost\\SQLEXPRESS;Database=TaskManager_DB;Integrated Security=True;TrustServerCertificate=True"
